apiVersion: v1
kind: Secret
metadata:
  name: objstore-secret
  namespace: mycnif-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTZPRFU1TUZNRjI2TlVMT1A=
  AWS_SECRET_ACCESS_KEY: Sjk1aW5yRTB3aDBJTEJLVEp0OTcvVjIxUTMvNkhUMzJDaHV5T0ROaw==



