# This rule is not used by the project mycninf itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mycninf.test.erwanleblond.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mycninf
    app.kubernetes.io/managed-by: kustomize
  name: objstore-admin-role
rules:
- apiGroups:
  - mycninf.test.erwanleblond.com
  resources:
  - objstores
  verbs:
  - '*'
- apiGroups:
  - mycninf.test.erwanleblond.com
  resources:
  - objstores/status
  verbs:
  - get
